import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'

export default function Events({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          <Image src="/logo_black.png" alt="logo" height={30} width={30} />
          <Link href="/">Home</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((event) => (
          <Link className="" href={`/events/${event.id}`} key={event.id}>
            <Image
              src={event.image}
              alt={event.title}
              height={300}
              width={300}
            />
            <h2>{event.title}</h2>
          </Link>
        ))}
      </main>
      <footer>
        <p>2023 time code - A Project</p>
      </footer>
    </>
  )
}

export async function getStaticProps() {
  const { allEvents } = await import('/data/data.json')
  const data = allEvents
  return { props: { data } }
}
