import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav>
          <Image src="/logo_black.png" alt="logo" height={30} width={30} />
          <Link href="/">Home</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <div>
          {data.map((event) => (
            <Link className="" href={`events/${event.id}`} key={event.id}>
              <Image
                src={event.image}
                width={300}
                height={200}
                alt={event.title}
              />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </Link>
          ))}
        </div>
      </main>
      <footer>
        <p>2023 time code - A Project</p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json')
  const data = events_categories
  return {
    props: {
      data
    } // will be passed to the page component as props
  }
}
